---
kind: Namespace
apiVersion: v1
metadata:
  name: test
  labels:
    name: test

---
kind: Namespace
apiVersion: v1
metadata:
  name: qa
  labels:
    name: qa

---
kind: Namespace
apiVersion: v1
metadata:
  name: dev
  labels:
    name: dev