---
kind: Namespace
apiVersion: v1
metadata:
  name: dev
  labels:
    name: dev

---
kind: Namespace
apiVersion: v1
metadata:
  name: qa
  labels:
    name: qa

---
kind: Namespace
apiVersion: v1
metadata:
  name: prod
  labels:
    name: prod