---
#single pod with duplicate port
apiVersion: v1
kind: Pod
metadata:
  name: multicn_duplicate-ports
  namespace: facebook
  labels:
    app: httpd
    tier: frontend-backend
    version: v1
spec:
  containers:
  - name: httpd1
    image: httpd
    ports:
    - containerPort: 80
  - name: httpd2
    image: httpd
    ports:
    - containerPort: 80
  